networks:
  gebi-network:

volumes:
  sql_server_gebi:

services:
  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx-gebi
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      gebi-network:

  laravel:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: laravel-gebi
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      gebi-network:

  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - sql_server_gebi:/var/opt/mssql
    environment:
      TZ: 'America/Sao_Paulo'
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'GEBI2025**'
    ports:
      - '1433:1433'
    networks:
        gebi-network:

